services:
  nemoclaw-controller:
    image: node:22-bookworm
    ports:
      - "18789:18789"
      - "18788:18788"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    working_dir: /app
    dns:
      - 8.8.8.8
    command: bash -c "node bin/nemoclaw.js start && tail -f /dev/null"
    environment:
      - TELEGRAM_BOT_TOKEN=8637805551:AAGdhOIhSodK1nx3lluUtT8luvU4RYq-tH8
      - NVIDIA_API_KEY=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
      - NEMOCLAW_SANDBOX_NAME=my-assistant
